# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
weather = pd.read_csv("../output_Data/Weather Data 2")
weather

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,County,Date
0,Cherskiy,68.7500,161.3000,274.60,94,15,7.89,RU,1627385932
1,Arman',59.7000,150.1667,288.29,66,78,2.75,RU,1627385932
2,Busselton,-33.6500,115.3333,282.64,62,93,6.70,AU,1627385933
3,Marialva,-23.4850,-51.7917,292.41,41,22,1.75,BR,1627385933
4,Luleå,65.5842,22.1547,295.19,60,0,4.12,SE,1627385934
...,...,...,...,...,...,...,...,...,...
561,Glenwood Springs,39.5505,-107.3248,293.72,68,1,0.00,US,1627386166
562,Aykhal,66.0000,111.5000,301.04,43,20,2.48,RU,1627386166
563,Opuwo,-18.0607,13.8400,297.46,18,0,5.50,NaN,1627386167
564,Riohacha,11.5444,-72.9072,299.33,87,94,3.70,CO,1627386100
565,Bintulu,3.1667,113.0333,302.38,79,20,0.00,MY,1627386167

In [3]:
weather.describe()

,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Date
count,566.000000,566.000000,566.000000,566.000000,566.000000,566.000000,5.660000e+02
mean,19.419262,20.762009,295.125459,67.775618,54.233216,3.785919,1.627386e+09
std,33.814371,89.921961,8.367159,24.217616,38.182404,2.712647,8.491802e+01
min,-54.800000,-175.200000,273.770000,5.000000,0.000000,0.000000,1.627386e+09
25%,-8.744825,-56.373300,290.047500,57.250000,12.250000,1.772500,1.627386e+09
50%,23.643450,23.160800,296.775000,75.000000,65.000000,3.410000,1.627386e+09
75%,48.895850,100.422625,300.255000,87.000000,90.000000,5.147500,1.627386e+09
max,78.218600,179.316700,317.910000,100.000000,100.000000,18.520000,1.627386e+09

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [4]:
# Configure maps
gmaps.configure(api_key=g_key)

#latitude and longitude
locations = weather[["Lat", "Lng"]]

# Humidity
humidity = weather["Humidity"]

#Heatmap
fig = gmaps.figure(center=(46.0, -5.0), zoom_level=2)
max_intensity = np.max(humidity)

#Heat layer
heat_layer = gmaps.heatmap_layer(locations, weights = humidity, dissipating=False, max_intensity=100, point_radius=3)

#Add layer
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows with null values.

In [5]:
city_weather = weather.loc[(weather["Wind Speed"]<=10) & (weather["Cloudiness"]==0) & (weather["Max Temp"]>=65) & \
                          (weather["Max Temp"]>=80)].dropna()
city_weather

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,County,Date
4,Luleå,65.5842,22.1547,295.19,60,0,4.12,SE,1627385934
5,East London,-33.0153,27.9116,302.67,14,0,7.20,ZA,1627385934
7,Kristiansund,63.1115,7.7320,299.18,60,0,4.63,NO,1627385935
16,Kiryat Gat,31.6100,34.7642,307.26,38,0,6.99,IL,1627385938
19,Byron Bay,-28.6500,153.6167,288.74,73,0,5.00,AU,1627385692
20,Valkeala,60.9401,26.7979,304.99,30,0,2.57,FI,1627385940
29,Concepción,-36.8270,-73.0498,275.04,93,0,1.54,CL,1627385944
54,Tromsø,69.6496,18.9570,297.51,68,0,4.63,NO,1627385696
67,Baharly,38.4362,57.4316,313.24,12,0,5.39,TM,1627385958
71,Korla,41.7597,86.1469,311.24,11,0,2.79,CN,1627385960
79,Port Elizabeth,-33.9180,25.5701,301.54,18,0,6.17,ZA,1627385782
99,Lempäälä,61.3167,23.7500,303.69,33,0,4.63,FI,1627385971
107,Erzin,36.9559,36.2000,311.44,33,0,4.40,TR,1627385975
128,Chu,43.5983,73.7614,307.72,19,0,7.44,KZ,1627385984
130,Talcahuano,-36.7167,-73.1167,274.97,93,0,1.54,CL,1627385985
140,Ekangala,-25.6962,28.7492,289.98,23,0,4.31,ZA,1627385988
150,Atocha,-20.9333,-66.2333,273.77,42,0,8.06,BO,1627385992
152,Arraial do Cabo,-22.9661,-42.0278,295.07,73,0,3.09,BR,1627385993
177,Ballina,-28.8667,153.5667,287.25,88,0,2.57,AU,1627386004
183,Marfino,55.7028,37.3822,301.75,28,0,3.00,RU,1627386007
197,Denizli Province,37.8402,29.0698,306.62,17,0,4.52,TR,1627386013
223,Gazojak,41.1875,61.4036,311.33,11,0,8.79,TM,1627386023
232,Itacoatiara,-3.1431,-58.4442,299.43,60,0,1.05,BR,1627386027
236,Sirte,31.2089,16.5887,302.04,53,0,5.79,LY,1627386029
245,Bredasdorp,-34.5322,20.0403,293.77,37,0,2.57,ZA,1627386034
252,Ürümqi,43.8010,87.6005,310.68,13,0,4.00,CN,1627386036
253,Coyhaique,-45.5752,-72.0662,275.12,80,0,2.06,CL,1627386037
270,Mastic Beach,40.7668,-72.8521,297.77,83,0,1.54,US,1627386043
276,Abu Samrah,35.3029,37.1841,311.28,16,0,6.87,SY,1627386046
293,Mizdah,31.4451,12.9801,305.92,21,0,4.12,LY,1627386053
299,Kruisfontein,-34.0033,24.7314,300.31,21,0,9.80,ZA,1627386056
304,Osijek,45.5511,18.6939,310.05,31,0,3.60,HR,1627386058
317,Tagāb,34.8550,69.6492,313.10,13,0,5.08,AF,1627386064
328,Shīeli,44.1667,66.7500,307.61,14,0,7.84,KZ,1627386068
349,Nālūt,30.3333,10.8500,309.70,11,0,2.28,LY,1627386077
356,Itaituba,-4.2761,-55.9836,297.24,94,0,0.00,BR,1627386080
362,Kozan,37.4552,35.8157,311.65,15,0,8.60,TR,1627386083
370,Nizhniy Mamon,50.1937,40.5083,304.11,25,0,3.57,RU,1627386087
377,Guerrero Negro,27.9769,-114.0611,292.53,85,0,3.71,MX,1627386089
404,Grindavik,63.8424,-22.4338,287.12,82,0,7.72,IS,1627386101
434,Mehamn,71.0357,27.8492,285.12,76,0,2.57,NO,1627386114
436,Sakakah,29.9697,40.2064,317.91,10,0,5.09,SA,1627386115
443,Santa Luzia,-19.7697,-43.8514,292.23,77,0,1.03,BR,1627386118
447,Rio de Janeiro,-22.9028,-43.2075,299.12,72,0,3.60,BR,1627386006
452,Suez,29.9737,32.5263,310.41,22,0,5.05,EG,1627386122
468,Noumea,-22.2763,166.4572,290.14,69,0,3.83,NC,1627386128
489,Mossamedes,-15.1961,12.1522,298.55,46,0,4.60,AO,1627386136
508,São João da Barra,-21.6403,-41.0511,293.20,61,0,4.54,BR,1627386144
510,Sidi Ali,36.0998,0.4206,301.27,53,0,5.54,DZ,1627386145
519,Oropesa,-13.5928,-71.7719,275.07,69,0,1.03,PE,1627386149
524,Pinawa,50.1489,-95.8811,288.49,75,0,1.23,CA,1627386151
535,Maun,-19.9833,23.4167,293.13,30,0,3.60,BW,1627386155
538,Pahrump,36.2083,-115.9839,298.21,58,0,1.37,US,1627386157
551,Plettenberg Bay,-34.0527,23.3716,295.78,42,0,3.53,ZA,1627386162
557,Caucaia,-3.7361,-38.6531,300.97,67,0,6.69,BR,1627385991

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [6]:
# Variable hotel_df
hotel_df = city_weather.loc[:,["City", "County", "Lat", "Lng"]]

# Adding column "Hotel Name" to Dataframe
hotel_df["Hotel Name"] = ""
hotel_df
hotel_df.rename(columns={"County": "Country"})

                  City Country      Lat       Lng Hotel Name
4                Luleå      SE  65.5842   22.1547
5          East London      ZA -33.0153   27.9116
7         Kristiansund      NO  63.1115    7.7320
16          Kiryat Gat      IL  31.6100   34.7642
19           Byron Bay      AU -28.6500  153.6167
20            Valkeala      FI  60.9401   26.7979
29          Concepción      CL -36.8270  -73.0498
54              Tromsø      NO  69.6496   18.9570
67             Baharly      TM  38.4362   57.4316
71               Korla      CN  41.7597   86.1469
79      Port Elizabeth      ZA -33.9180   25.5701
99            Lempäälä      FI  61.3167   23.7500
107              Erzin      TR  36.9559   36.2000
128                Chu      KZ  43.5983   73.7614
130         Talcahuano      CL -36.7167  -73.1167
140           Ekangala      ZA -25.6962   28.7492
150             Atocha      BO -20.9333  -66.2333
152    Arraial do Cabo      BR -22.9661  -42.0278
177            Ballina      AU -28.8667  153.5667
183            Marfino      RU  55.7028   37.3822
197   Denizli Province      TR  37.8402   29.0698
223            Gazojak      TM  41.1875   61.4036
232        Itacoatiara      BR  -3.1431  -58.4442
236              Sirte      LY  31.2089   16.5887
245         Bredasdorp      ZA -34.5322   20.0403
252             Ürümqi      CN  43.8010   87.6005
253          Coyhaique      CL -45.5752  -72.0662
270       Mastic Beach      US  40.7668  -72.8521
276         Abu Samrah      SY  35.3029   37.1841
293             Mizdah      LY  31.4451   12.9801
299       Kruisfontein      ZA -34.0033   24.7314
304             Osijek      HR  45.5511   18.6939
317              Tagāb      AF  34.8550   69.6492
328             Shīeli      KZ  44.1667   66.7500
349              Nālūt      LY  30.3333   10.8500
356           Itaituba      BR  -4.2761  -55.9836
362              Kozan      TR  37.4552   35.8157
370      Nizhniy Mamon      RU  50.1937   40.5083
377     Guerrero Negro      MX  27.9769 -114.0611
404          Grindavik      IS  63.8424  -22.4338
434             Mehamn      NO  71.0357   27.8492
436            Sakakah      SA  29.9697   40.2064
443        Santa Luzia      BR -19.7697  -43.8514
447     Rio de Janeiro      BR -22.9028  -43.2075
452               Suez      EG  29.9737   32.5263
468             Noumea      NC -22.2763  166.4572
489         Mossamedes      AO -15.1961   12.1522
508  São João da Barra      BR -21.6403  -41.0511
510           Sidi Ali      DZ  36.0998    0.4206
519            Oropesa      PE -13.5928  -71.7719
524             Pinawa      CA  50.1489  -95.8811
535               Maun      BW -19.9833   23.4167
538            Pahrump      US  36.2083 -115.9839
551    Plettenberg Bay      ZA -34.0527   23.3716
557            Caucaia      BR  -3.7361  -38.6531

In [7]:
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
params ={"type" : "hotel",
        "Keyword" : "hotel",
        "radius" : 5000,
        "key" : g_key}

In [11]:
for index, row in hotel_df.iterrows():
    #retrieve city name, lat, lng from df
    lat = row["Lat"]
    lng = row["Lng"]
    city_name = row["City"]
    # adding keyword to pramas dict
    params["location"] = f"{lat}, {lng}"
    
    # Url and API request
    
    print(f"Retrieving Results for Index {index}: {city_name}.")
    response = requests.get(base_url, params=params).json()
    
    # result
    results = response["results"]
    
    # Dataframe to hold hotel names
    try:
        print(f"Closest hotel in {city_name} is {results[0]['name']}.")
        hotel_df.loc[index, "Hotel Name"]= results[0]['name']
        
        #show missing result, if no hotel found
    except (KeyError, IndexError):
        print("Missing result...... skipping.")
    print("--------------------------")
    
    # Wait before making another api request to avoid error
    #time.sleep(1)

print("-------- End------------------")

Retrieving Results for Index 4: Luleå.
Closest hotel in Luleå is Luleå.
--------------------------
Retrieving Results for Index 5: East London.
Closest hotel in East London is East London.
--------------------------
Retrieving Results for Index 7: Kristiansund.
Closest hotel in Kristiansund is Kristiansund.
--------------------------
Retrieving Results for Index 16: Kiryat Gat.
Closest hotel in Kiryat Gat is Kiryat Gat.
--------------------------
Retrieving Results for Index 19: Byron Bay.
Closest hotel in Byron Bay is Byron Bay.
--------------------------
Retrieving Results for Index 20: Valkeala.
Closest hotel in Valkeala is Kouvola.
--------------------------
Retrieving Results for Index 29: Concepción.
Closest hotel in Concepción is Concepción.
--------------------------
Retrieving Results for Index 54: Tromsø.
Closest hotel in Tromsø is Tromsø.
--------------------------
Retrieving Results for Index 67: Baharly.
Closest hotel in Baharly is Baharly.
--------------------------
Retrieving Results for Index 71: Korla.
Closest hotel in Korla is Bayingolin Mongol Autonomous Prefecture.
--------------------------
Retrieving Results for Index 79: Port Elizabeth.
Closest hotel in Port Elizabeth is Gqeberha.
--------------------------
Retrieving Results for Index 99: Lempäälä.
Closest hotel in Lempäälä is Lempäälä.
--------------------------
Retrieving Results for Index 107: Erzin.
Closest hotel in Erzin is Erzin.
--------------------------
Retrieving Results for Index 128: Chu.
Closest hotel in Chu is Shu.
--------------------------
Retrieving Results for Index 130: Talcahuano.
Closest hotel in Talcahuano is Talcahuano.
--------------------------
Retrieving Results for Index 140: Ekangala.
Closest hotel in Ekangala is Bronkhorstspruit.
--------------------------
Retrieving Results for Index 150: Atocha.
Closest hotel in Atocha is Atocha.
--------------------------
Retrieving Results for Index 152: Arraial do Cabo.
Closest hotel in Arraial do Cabo is Arraial do Cabo.
--------------------------
Retrieving Results for Index 177: Ballina.
Closest hotel in Ballina is Ballina.
--------------------------
Retrieving Results for Index 183: Marfino.
Closest hotel in Marfino is Moscow.
--------------------------
Retrieving Results for Index 197: Denizli Province.
Closest hotel in Denizli Province is Denizli.
--------------------------
Retrieving Results for Index 223: Gazojak.
Closest hotel in Gazojak is Pitnak.
--------------------------
Retrieving Results for Index 232: Itacoatiara.
Closest hotel in Itacoatiara is Itacoatiara.
--------------------------
Retrieving Results for Index 236: Sirte.
Closest hotel in Sirte is Sirte.
--------------------------
Retrieving Results for Index 245: Bredasdorp.
Closest hotel in Bredasdorp is Bredasdorp.
--------------------------
Retrieving Results for Index 252: Ürümqi.
Closest hotel in Ürümqi is Ürümqi.
--------------------------
Retrieving Results for Index 253: Coyhaique.
Closest hotel in Coyhaique is Coyhaique.
--------------------------
Retrieving Results for Index 270: Mastic Beach.
Closest hotel in Mastic Beach is Shirley.
--------------------------
Retrieving Results for Index 276: Abu Samrah.
Closest hotel in Abu Samrah is Suruj.
--------------------------
Retrieving Results for Index 293: Mizdah.
Closest hotel in Mizdah is Mizdah.
--------------------------
Retrieving Results for Index 299: Kruisfontein.
Closest hotel in Kruisfontein is Humansdorp.
--------------------------
Retrieving Results for Index 304: Osijek.
Closest hotel in Osijek is Osijek.
--------------------------
Retrieving Results for Index 317: Tagāb.
Closest hotel in Tagāb is Tagab.
--------------------------
Retrieving Results for Index 328: Shīeli.
Closest hotel in Shīeli is Shieli.
--------------------------
Retrieving Results for Index 349: Nālūt.
Missing result...... skipping.
--------------------------
Retrieving Results for Index 356: Itaituba.
Closest hotel in Itaituba is Itaituba.
--------------------------
Retrieving Results for Index 362: Kozan.
Closest hotel in Kozan is Kozan.
--------------------------
Retrieving Results for Index 370: Nizhniy Mamon.
Closest hotel in Nizhniy Mamon is Verkhniy Mamon.
--------------------------
Retrieving Results for Index 377: Guerrero Negro.
Closest hotel in Guerrero Negro is Guerrero Negro.
--------------------------
Retrieving Results for Index 404: Grindavik.
Closest hotel in Grindavik is Grindavik.
--------------------------
Retrieving Results for Index 434: Mehamn.
Closest hotel in Mehamn is Mehamn.
--------------------------
Retrieving Results for Index 436: Sakakah.
Closest hotel in Sakakah is Sakaka.
--------------------------
Retrieving Results for Index 443: Santa Luzia.
Closest hotel in Santa Luzia is Santa Luzia.
--------------------------
Retrieving Results for Index 447: Rio de Janeiro.
Closest hotel in Rio de Janeiro is Rio de Janeiro.
--------------------------
Retrieving Results for Index 452: Suez.
Closest hotel in Suez is Suez.
--------------------------
Retrieving Results for Index 468: Noumea.
Closest hotel in Noumea is Nouméa.
--------------------------
Retrieving Results for Index 489: Mossamedes.
Closest hotel in Mossamedes is Namibe.
--------------------------
Retrieving Results for Index 508: São João da Barra.
Closest hotel in São João da Barra is Grussaí.
--------------------------
Retrieving Results for Index 510: Sidi Ali.
Closest hotel in Sidi Ali is Sidi Ali.
--------------------------
Retrieving Results for Index 519: Oropesa.
Closest hotel in Oropesa is Oropesa.
--------------------------
Retrieving Results for Index 524: Pinawa.
Closest hotel in Pinawa is Pinawa.
--------------------------
Retrieving Results for Index 535: Maun.
Closest hotel in Maun is Maun.
--------------------------
Retrieving Results for Index 538: Pahrump.
Closest hotel in Pahrump is Pahrump.
--------------------------
Retrieving Results for Index 551: Plettenberg Bay.
Closest hotel in Plettenberg Bay is Plettenberg Bay.
--------------------------
Retrieving Results for Index 557: Caucaia.
Closest hotel in Caucaia is Caucaia.
--------------------------
-------- End------------------

In [13]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>County</dt><dd>{County}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [14]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations, info_box_content = hotel_info)

fig.add_layer(markers)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))